version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  install:
    commands:
        - npm install
        - npm install -g node-lambda
        - node-lambda deploy
  build:
    commands:
        node-lambda package
artifacts:
  files:
      - build/testDupe-production.zip
  #discard-paths: yes
  #base-directory: location